# This workflow will do a clean installation of node dependencies and run tests across different versions of node

name: Calendar CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Test project
        run: npm run ghcitests
        env:
          MODE: ${{ vars.MODE }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
          TEST_USER_PASS: ${{ secrets.TEST_USER_PASS }}

  # Development environment
  development:
    runs-on: ubuntu-latest
    environment: dev
    needs: [test]

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
